production:
  adapter: mysql2
  database: sonny
  host: localhost
  username: root
  password:
  encoding: utf8

development:
  adapter: mysql2
  database: sonny-dev
  host: localhost
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: sonny-test
  host: localhost
  username: root
  password:
  encoding: utf8